----------------- CREATE ALL SNOWFLAKE OBJECTS FOR TESTING


--- DATABASE

CREATE DATABASE DATA_CATALOG;

COMMENT ON DATABASE DATA_CATALOG IS 'This is a Data Catalog Database';

--- SCHEMAS

CREATE SCHEMA DATA_CATALOG_SAMPLE;
CREATE SCHEMA DATA_CATALOG_SAMPLE_2;

COMMENT ON SCHEMA DATA_CATALOG.DATA_CATALOG_SAMPLE IS 'This is a Data Catalog schema';
COMMENT ON SCHEMA DATA_CATALOG.DATA_CATALOG_SAMPLE_2 IS 'This is the second example of a Data Catalog schema';

--- TABLES

CREATE OR REPLACE TABLE DATA_CATALOG.DATA_CATALOG_SAMPLE.SALES (
    PRODUCT_ID NUMBER COMMENT 'This is a PRODUCT_ID column',
    PRODUCT_NAME TEXT COMMENT 'This is a PRODUCT_NAME column'
) COMMENT='This is a SALES table';

CREATE OR REPLACE TABLE DATA_CATALOG.DATA_CATALOG_SAMPLE.CUSTOMERS (
    CUSTOMER_ID NUMBER COMMENT 'This is a CUSTOMER_ID column',
    CUSTOMER_NAME TEXT COMMENT 'This is a CUSTOMER_NAME column'
) COMMENT='This is a CUSTOMERS table';

CREATE OR REPLACE TABLE DATA_CATALOG.DATA_CATALOG_SAMPLE_2.CATEGORY (
    CATEGORY_ID NUMBER COMMENT 'This is a CATEGORY_ID column',
    CATEGORY_NAME TEXT COMMENT 'This is a CATEGORY_NAME column'
) COMMENT='This is a CATEGORY table';

CREATE OR REPLACE TABLE DATA_CATALOG.DATA_CATALOG_SAMPLE_2.SPENDINGS (
    SPENDING_ID NUMBER COMMENT 'This is a SPENDING_ID column',
    SPENDING_NAME TEXT COMMENT 'This is a SPENDING_NAME column'
) COMMENT='This is a SPENDINGS table';

--- CREATE AGG TABLE/MATERIALIZED VIEW

create or replace table data_catalog_agg (
	DB_NAME TEXT,
	DB_DESCRIPTION TEXT,
	SCHEMA_NAME TEXT,
	SCHEMA_DESCRIPTION TEXT,
	TABLE_NAME TEXT,
	TABLE_DESCRIPTION TEXT,
	COLUMN_NAME TEXT,
	COLUMN_DESCRIPTION TEXT,
	DATA_TYPE TEXT,
	IS_NULLABLE BOOLEAN,
	CHARACTER_MAXIMUM_LENGTH NUMBER,
	NUMERIC_PRECISION NUMBER)

--- CREATE DATA LINEAGE TABLE

create or replace table data_catalog.public.data_catalog_lineage (
	DB_NAME TEXT,
	SCHEMA_NAME TEXT,
	TABLE_NAME TEXT,
	SOURCE_TABLE TEXT,
    QUERY TEXT)
