INSERT INTO DATA_CATALOG_AGG(
	DBMS,
	DATABASE_NAME,
	SCHEMA_NAME,
	TABLE_NAME,
	TABLE_DESCRIPTION,
	COLUMN_NAME,
	COLUMN_DESCRIPTION,
	DATA_TYPE,
	IS_NULLABLE,
	CHARACTER_MAXIMUM_LENGTH,
	NUMERIC_PRECISION
)
VALUES
{values}