"""Adding more tables

Revision ID: 016a356b888f
Revises: be1ba4d07099
Create Date: 2022-08-30 20:57:38.994408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016a356b888f'
down_revision = 'be1ba4d07099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_catalog_agg',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('database_decription', sa.String(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('schema_description', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('table_description', sa.String(), nullable=True),
    sa.Column('column_name', sa.String(), nullable=True),
    sa.Column('column_description', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('is_nullable', sa.String(), nullable=True),
    sa.Column('character_maximum_length', sa.String(), nullable=True),
    sa.Column('numeric_precision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_catalog_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('database_name', sa.String(), nullable=True),
    sa.Column('schema_name', sa.String(), nullable=True),
    sa.Column('table_name', sa.String(), nullable=True),
    sa.Column('source_table', sa.String(), nullable=True),
    sa.Column('source_query', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('doors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='cars_pkey')
    )
    op.drop_table('data_catalog_lineage')
    op.drop_table('data_catalog_agg')
    # ### end Alembic commands ###
