"""Fixed column name

Revision ID: 6b8055d588b2
Revises: 016a356b888f
Create Date: 2022-08-30 21:49:03.191955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8055d588b2'
down_revision = '016a356b888f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catalog_agg', sa.Column('database_description', sa.String(), nullable=True))
    op.drop_column('data_catalog_agg', 'database_decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_catalog_agg', sa.Column('database_decription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('data_catalog_agg', 'database_description')
    # ### end Alembic commands ###
